package br.skylight.commons.dli.enums;

public enum PointingModeState {

	NO_VALUE,
	ANGLE_RELATIVE_TO_AV,
	SLEWING_RATE_RELATIVE_TO_AV,
	SLEWING_RATE_RELATIVE_TO_INERTIAL,
	LAT_LONG_SLAVED,
	RESERVED_6,RESERVED_7,RESERVED_8,RESERVED_9;
	
}
